spring:
  application:
    name: simple-backend
  datasource:
    url: jdbc:h2:mem:taskdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: my-observable-app-backend #tag added to all metrics
    distribution:
      percentiles-histogram:
        http.server.requests: true
